port: 3001

settings:
  csrf: false
  debug: false
  loggerFormat: tiny
  session:
    cookie:
      sameSite: lax
  disk:
    driver: 'local'
    local:
      directory: 'uploaded'
  jwt:
    secret: W0vSaMhSjjeSAIvAgaueh3rhi5LY2avXHJTrJcovGVk=
  multipartRequests:
    fileSizeLimit: 4096000
    fileNumberLimit: 10
icq:
  uri: https://api.icq.net/bot/v1
  token: 001.4039253446.2905774098:754618342
  botId: 754618342
  chatId: @quanna.dev
mongodb:
  uri: mongodb+srv://mediaservericq:24EcHAYkvsDn0yhb@cluster0-zikxw.mongodb.net/media-server?retryWrites=true&w=majority
